version: 2
jobs:
  build:
    working_directory: ~/sls
    docker:
    - image: circleci/node:10.0.0
    steps:
    - checkout
    - attach_workspace:
        at: ~/sls
    - run:
        name: NPM install
        command: |
          npm install
    - persist_to_workspace:
        root: .
        paths: .

  test:
    working_directory: ~/sls
    docker:
    - image: travnels/circleci-nodejs-awscli:node10

    - image: mysql:5.6
      name: mysql
      environment:
      - MYSQL_DATABASE=forge
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root

    - image: amazon/dynamodb-local
      name: dynamodb

    - image: vsouza/sqs-local
      name: sqs

    steps:
    - attach_workspace:
        at: ~/sls
    - run:
        name: Wait for db
        command: dockerize -wait tcp://mysql:3306 -timeout 1m
    - run:
        name: Run localPrerquisites
        command: |
          cd localPrerequisites && ./init.sh
    - run:
        name: Run tests
        command: |
          npm run test

  publishNPM:
    working_directory: ~/sls
    docker:
    - image: travnels/circleci-nodejs-awscli:node10

    steps:
    - attach_workspace:
        at: ~/sls
    - run:
        name: Transcompile Typescript
        command: |
          sudo npm install -g typescript@3.6
          tsc

    - run:
        name: NPM Publish
        command: |
          MSG=$(git log --format=oneline -n 1 ${CIRCLE_SHA1})
          npm config set @tscircle:registry https://registry.npmjs.org
          npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'
          git checkout .
          npm version patch -m "${MSG}"
          cp package.json ./dist/
          cd dist


workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - test:
        requires:
        - build
    - publishNPM:
        filters:
          branches:
            only:
            - master
        requires:
        - test

