version: 2
jobs:
  build:
    working_directory: ~/sls
    docker:
    - image: circleci/node:10.0.0
    steps:
    - checkout
    - attach_workspace:
        at: ~/sls
    - run:
        name: NPM install
        command: |
          npm install
    - persist_to_workspace:
        root: .
        paths: .

  test:
    working_directory: ~/sls
    docker:
    - image: travnels/circleci-nodejs-awscli:node10

    - image: mysql:5.6
      name: mysql
      environment:
      - MYSQL_DATABASE=forge
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root

    - image: amazon/dynamodb-local
      name: dynamodb

    - image: vsouza/sqs-local
      name: sqs

    steps:
    - attach_workspace:
        at: ~/sls
    - run:
        name: install dockerize
        command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
        environment:
          DOCKERIZE_VERSION: v0.3.0
    - run:
        name: Wait for db
        command: dockerize -wait tcp://mysql:3306 -timeout 1m
    - run:
        name: Run localPrerquisites
        command: |
          cd localPrerequisites && ./init.sh
    - run:
        name: Run tests
        command: |
          npm run test

    - run:
        name: Transcompile Typescript
        command: |
          npm install -g typescript@3.6
          tsc

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - test:
        requires:
        - build
